/* eslint-disable import/prefer-default-export */

export const counter = {
  INCREMENT: 'COUNTER_INCREMENT',
  DECREMENT: 'COUNTER_DECREMENT',
};

export const home = {
  REQUEST_API_CONTENT: 'REQUEST_API_CONTENT',
  REQUEST_API_CONTENT_SUCCESS: 'REQUEST_API_CONTENT_SUCCESS',
  REQUEST_API_CONTENT_FAIL: 'REQUEST_API_CONTENT_FAIL',
};

export const login = {
  SAVE_GITHUB_CREDENTIALS: 'SAVE_GITHUB_CREDENTIALS',
  REQUEST_GITHUB_TOKEN: 'REQUEST_GITHUB_TOKEN',
  REQUEST_GITHUB_TOKEN_SUCCESS: 'REQUEST_GITHUB_TOKEN_SUCCESS',
  REQUEST_GITHUB_TOKEN_FAILURE: 'REQUEST_GITHUB_TOKEN_FAILURE',
  SAVE_REDIRECT: 'SAVE_REDIRECT',
};
